/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false env.d.ts` (hash: d0ba234eb97d4a4003830b2a73b44fec)
interface __BaseEnv_Env {
	DEVIN_ORG_ID: string;
	DEVIN_BASE_URL: string;
	DEVIN_API_KEY: string;
	Workspace: DurableObjectNamespace<import("./src/server").Workspace>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Workspace";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEVIN_ORG_ID" | "DEVIN_BASE_URL" | "DEVIN_API_KEY">> {}
}
